//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlExplorer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlExplorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AcceptChanges {
            get {
                object obj = ResourceManager.GetObject("AcceptChanges", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Action_spellcheck_icon_1_1 {
            get {
                object obj = ResourceManager.GetObject("Action_spellcheck_icon_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddressBook {
            get {
                object obj = ResourceManager.GetObject("AddressBook", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignTextCenter {
            get {
                object obj = ResourceManager.GetObject("AlignTextCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignTextJustify {
            get {
                object obj = ResourceManager.GetObject("AlignTextJustify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignTextLeft {
            get {
                object obj = ResourceManager.GetObject("AlignTextLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AlignTextRight {
            get {
                object obj = ResourceManager.GetObject("AlignTextRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Available {
            get {
                object obj = ResourceManager.GetObject("Available", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Away {
            get {
                object obj = ResourceManager.GetObject("Away", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bold {
            get {
                object obj = ResourceManager.GetObject("Bold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Brush {
            get {
                object obj = ResourceManager.GetObject("Brush", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Bullets {
            get {
                object obj = ResourceManager.GetObject("Bullets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Busy {
            get {
                object obj = ResourceManager.GetObject("Busy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap c1new2 {
            get {
                object obj = ResourceManager.GetObject("c1new2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap c1watermark2 {
            get {
                object obj = ResourceManager.GetObject("c1watermark2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CalendarSchedule {
            get {
                object obj = ResourceManager.GetObject("CalendarSchedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CategorySalesByMonth {
            get {
                return ResourceManager.GetString("CategorySalesByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CategorySalesByQuarter {
            get {
                return ResourceManager.GetString("CategorySalesByQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CategorySalesByYear {
            get {
                return ResourceManager.GetString("CategorySalesByYear", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Chart {
            get {
                object obj = ResourceManager.GetObject("Chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ChartWizard {
            get {
                object obj = ResourceManager.GetObject("ChartWizard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Close2 {
            get {
                object obj = ResourceManager.GetObject("Close2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap code {
            get {
                object obj = ResourceManager.GetObject("code", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ColorGallery1 {
            get {
                object obj = ResourceManager.GetObject("ColorGallery1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Contents {
            get {
                object obj = ResourceManager.GetObject("Contents", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;Customers&gt;
        ///    &lt;CustomerID&gt;ALFKI&lt;/CustomerID&gt;
        ///    &lt;CompanyName&gt;Alfreds Futterkiste&lt;/CompanyName&gt;
        ///    &lt;ContactName&gt;Maria Anders&lt;/ContactName&gt;
        ///    &lt;ContactTitle&gt;Sales Representative&lt;/ContactTitle&gt;
        ///    &lt;Address&gt;Obere Str. 57&lt;/Address&gt;
        ///    &lt;City&gt;Berlin&lt;/City&gt;
        ///    &lt;PostalCode&gt;12209&lt;/PostalCode&gt;
        ///    &lt;Country&gt;Germany&lt;/Country&gt;
        ///    &lt;Phone&gt;030-0074321&lt;/Phone&gt;
        ///    &lt;Fax&gt;030-0076545&lt;/Fax&gt;
        ///  &lt;/Customers&gt;
        ///  &lt;Customers&gt;
        ///    &lt;CustomerID&gt;ANATR&lt;/Custo [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cut {
            get {
                object obj = ResourceManager.GetObject("Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Database {
            get {
                object obj = ResourceManager.GetObject("Database", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DecreaseIndent {
            get {
                object obj = ResourceManager.GetObject("DecreaseIndent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteComment {
            get {
                object obj = ResourceManager.GetObject("DeleteComment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap designers_wizards_80x80 {
            get {
                object obj = ResourceManager.GetObject("designers_wizards_80x80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap drives {
            get {
                object obj = ResourceManager.GetObject("drives", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Edit {
            get {
                object obj = ResourceManager.GetObject("Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EditComment {
            get {
                object obj = ResourceManager.GetObject("EditComment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot; msdata:MainDataTable=&quot;Employees&quot; msdata:UseCurrentLocale=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Employees&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///             [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Envelope1 {
            get {
                object obj = ResourceManager.GetObject("Envelope1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Diagnostics;
        ///using System.Data;
        ///using System.Drawing;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows.Forms;
        ///using C1.C1Excel;
        ///
        ///namespace ControlExplorer.Excel
        ///{
        ///    public partial class NumericFormatting : C1DemoForm
        ///    {
        ///        public NumericFormatting()
        ///        {
        ///            InitializeComponent();
        ///            AddDescription(&quot;This sample creates a sheet with several columns. Each column [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ExcelNumericFormatting {
            get {
                return ResourceManager.GetString("ExcelNumericFormatting", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap file {
            get {
                object obj = ResourceManager.GetObject("file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FirstRecord {
            get {
                object obj = ResourceManager.GetObject("FirstRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flashslide {
            get {
                object obj = ResourceManager.GetObject("flashslide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen {
            get {
                object obj = ResourceManager.GetObject("FolderOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FontColor {
            get {
                object obj = ResourceManager.GetObject("FontColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GrowFont {
            get {
                object obj = ResourceManager.GetObject("GrowFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hardDrive {
            get {
                object obj = ResourceManager.GetObject("hardDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help {
            get {
                object obj = ResourceManager.GetObject("Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HighlightColor {
            get {
                object obj = ResourceManager.GetObject("HighlightColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryBack {
            get {
                object obj = ResourceManager.GetObject("HistoryBack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HistoryForward {
            get {
                object obj = ResourceManager.GetObject("HistoryForward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Home {
            get {
                object obj = ResourceManager.GetObject("Home", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;Over 65 .NET controls, including the ones you can&apos;t get anywhere else. ComponentOne Studio for WinForms controls come packed with smart, code-free designers, endless built-in features that go above and beyond the out-of-the box experience, superior flexibility and the outstanding assurance that these controls can stand the test of time.
        ///&lt;/p&gt;
        ///&lt;h3&gt;What&apos;s New 2012 v3&lt;/h3&gt;
        ///&lt;hr/&gt;
        ///&lt;strong&gt;
        ///  &lt;span style=&quot;font-size:small&quot;&gt;C1Editor - RTF Support&lt;/span&gt;
        ///&lt;/strong&gt;
        ///&lt;br/&gt;
        ///&lt;table cellpadding=&quot;10&quot;&gt;
        ///  &lt;tr&gt;
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap IncreaseIndent {
            get {
                object obj = ResourceManager.GetObject("IncreaseIndent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Index {
            get {
                object obj = ResourceManager.GetObject("Index", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info2 {
            get {
                object obj = ResourceManager.GetObject("Info2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Italic {
            get {
                object obj = ResourceManager.GetObject("Italic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LastRecord {
            get {
                object obj = ResourceManager.GetObject("LastRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loadNew {
            get {
                object obj = ResourceManager.GetObject("loadNew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m01 {
            get {
                object obj = ResourceManager.GetObject("m01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m02 {
            get {
                object obj = ResourceManager.GetObject("m02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m03 {
            get {
                object obj = ResourceManager.GetObject("m03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m04 {
            get {
                object obj = ResourceManager.GetObject("m04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m05 {
            get {
                object obj = ResourceManager.GetObject("m05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m06 {
            get {
                object obj = ResourceManager.GetObject("m06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m07 {
            get {
                object obj = ResourceManager.GetObject("m07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m08 {
            get {
                object obj = ResourceManager.GetObject("m08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m09 {
            get {
                object obj = ResourceManager.GetObject("m09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m10 {
            get {
                object obj = ResourceManager.GetObject("m10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m11 {
            get {
                object obj = ResourceManager.GetObject("m11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap m12 {
            get {
                object obj = ResourceManager.GetObject("m12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mediaDrive {
            get {
                object obj = ResourceManager.GetObject("mediaDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] mlb {
            get {
                object obj = ResourceManager.GetObject("mlb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MonthlySalesByCategory {
            get {
                return ResourceManager.GetString("MonthlySalesByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Reports&gt;
        ///  &lt;!--Report *** Multi Across ***--&gt;
        ///  &lt;Report version=&quot;2.5.20061.195&quot;&gt;
        ///    &lt;Name&gt;Multi Across&lt;/Name&gt;
        ///    &lt;ReportInfo /&gt;
        ///    &lt;DataSource&gt;
        ///      &lt;ConnectionString&gt;Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|C1Demo.mdb;Persist Security Info=False&lt;/ConnectionString&gt;
        ///      &lt;RecordSource&gt;select * from categories
        ///order by categoryname desc&lt;/RecordSource&gt;
        ///    &lt;/DataSource&gt;
        ///    &lt;Layout&gt;
        ///      &lt;Width&gt;4554&lt;/Width&gt;
        ///      &lt;Orientation&gt;1&lt;/Orientation&gt;
        ///      &lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MultiColSubreport {
            get {
                return ResourceManager.GetString("MultiColSubreport", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap networkDrive {
            get {
                object obj = ResourceManager.GetObject("networkDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New {
            get {
                object obj = ResourceManager.GetObject("New", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap New2014 {
            get {
                object obj = ResourceManager.GetObject("New2014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewComment {
            get {
                object obj = ResourceManager.GetObject("NewComment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewContact {
            get {
                object obj = ResourceManager.GetObject("NewContact", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewEmail {
            get {
                object obj = ResourceManager.GetObject("NewEmail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newFolder {
            get {
                object obj = ResourceManager.GetObject("newFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewNote {
            get {
                object obj = ResourceManager.GetObject("NewNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewTask {
            get {
                object obj = ResourceManager.GetObject("NewTask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NextRecord {
            get {
                object obj = ResourceManager.GetObject("NextRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Numbering {
            get {
                object obj = ResourceManager.GetObject("Numbering", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon Offline {
            get {
                object obj = ResourceManager.GetObject("Offline", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Open {
            get {
                object obj = ResourceManager.GetObject("Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Options {
            get {
                object obj = ResourceManager.GetObject("Options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Orders&gt;
        ///&lt;Customer&gt;
        ///    &lt;NameEntry&gt;
        ///        &lt;FirstName&gt;Pierce&lt;/FirstName&gt;
        ///        &lt;LastName&gt;Bronson&lt;/LastName&gt;   
        ///        &lt;EMail&gt;bronson@hwood.com&lt;/EMail&gt;
        ///    &lt;/NameEntry&gt;
        ///    &lt;Order&gt;
        ///        &lt;Name&gt;Where the Sidewalk Ends&lt;/Name&gt;
        ///        &lt;Author&gt;Shel Silverstein&lt;/Author&gt;
        ///        &lt;Price&gt;$5.95&lt;/Price&gt;
        ///        &lt;Detail&gt;
        ///            &lt;Carrier&gt;United Airlines&lt;/Carrier&gt;
        ///            &lt;SKU&gt;411AAA&lt;/SKU&gt;
        ///        &lt;/Detail&gt;
        ///    &lt;/Order&gt;
        ///    &lt;Date&gt;7/7/97&lt;/Date&gt;
        ///&lt;/Cus [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap otherDrive {
            get {
                object obj = ResourceManager.GetObject("otherDrive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Paste {
            get {
                object obj = ResourceManager.GetObject("Paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pinned {
            get {
                object obj = ResourceManager.GetObject("Pinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PreviousRecord {
            get {
                object obj = ResourceManager.GetObject("PreviousRecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;DocumentElement&gt;
        ///  &lt;Products&gt;
        ///    &lt;ProductID&gt;1&lt;/ProductID&gt;
        ///    &lt;ProductName&gt;Chai&lt;/ProductName&gt;
        ///    &lt;SupplierID&gt;1&lt;/SupplierID&gt;
        ///    &lt;CategoryID&gt;1&lt;/CategoryID&gt;
        ///    &lt;QuantityPerUnit&gt;10 boxes x 20 bags&lt;/QuantityPerUnit&gt;
        ///    &lt;UnitPrice&gt;18&lt;/UnitPrice&gt;
        ///    &lt;UnitsInStock&gt;39&lt;/UnitsInStock&gt;
        ///    &lt;UnitsOnOrder&gt;0&lt;/UnitsOnOrder&gt;
        ///    &lt;ReorderLevel&gt;10&lt;/ReorderLevel&gt;
        ///    &lt;Discontinued&gt;false&lt;/Discontinued&gt;
        ///  &lt;/Products&gt;
        ///  &lt;Products&gt;
        ///    &lt;ProductID&gt;2&lt;/ProductID&gt;
        ///    &lt;Prod [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Properties {
            get {
                object obj = ResourceManager.GetObject("Properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string QuarterlySalesByCategory {
            get {
                return ResourceManager.GetString("QuarterlySalesByCategory", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Redo {
            get {
                object obj = ResourceManager.GetObject("Redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap refresh2 {
            get {
                object obj = ResourceManager.GetObject("refresh2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap rename {
            get {
                object obj = ResourceManager.GetObject("rename", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Repeat {
            get {
                object obj = ResourceManager.GetObject("Repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Report {
            get {
                object obj = ResourceManager.GetObject("Report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Reports&gt;
        ///  &lt;!--Report *** 01: Alternating Background (Greenbar report) ***--&gt;
        ///  &lt;Report version=&quot;2.5.20072.239&quot;&gt;
        ///    &lt;Name&gt;Alternating Background&lt;/Name&gt;
        ///    &lt;ReportInfo /&gt;
        ///    &lt;DataSource&gt;
        ///      &lt;ConnectionString&gt;Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|C1Demo.mdb;Persist Security Info=False&lt;/ConnectionString&gt;
        ///      &lt;RecordSource&gt;SELECT Categories.*, Products.*
        ///FROM Categories INNER JOIN Products ON Categories.CategoryID = Products.CategoryID;
        ///&lt;/RecordSour [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 abstract
        ///as
        ///base
        ///bool
        ///break
        ///byte
        ///case
        ///catch
        ///char
        ///checked
        ///class
        ///const
        ///continue
        ///decimal
        ///default
        ///delegate
        ///do
        ///double
        ///else
        ///enum
        ///event
        ///explicit
        ///extern
        ///false
        ///finally
        ///fixed
        ///float
        ///for
        ///foreach
        ///goto
        ///if
        ///implicit
        ///in
        ///int
        ///interface
        ///internal
        ///is
        ///lock
        ///long
        ///namespace
        ///new
        ///null
        ///object
        ///operator
        ///out
        ///override
        ///params
        ///private
        ///protected
        ///public
        ///readonly
        ///ref
        ///return
        ///sbyte
        ///sealed
        ///short
        ///sizeof
        ///stackalloc
        ///static
        ///string
        ///struct
        ///switch
        ///this
        ///throw
        ///true
        ///try
        ///typeof
        ///uint
        ///ulong
        ///u [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string reservedWords {
            get {
                return ResourceManager.GetString("reservedWords", resourceCulture);
            }
        }
        
        internal static byte[] route66 {
            get {
                object obj = ResourceManager.GetObject("route66", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1251\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1049\deflangfe1049\themelang1049\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset204\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset204\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f2\fbidi \fmodern\fcharset204\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fchars [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sample {
            get {
                return ResourceManager.GetString("sample", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Save1 {
            get {
                object obj = ResourceManager.GetObject("Save1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAll {
            get {
                object obj = ResourceManager.GetObject("SaveAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SaveAs {
            get {
                object obj = ResourceManager.GetObject("SaveAs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Schedule {
            get {
                object obj = ResourceManager.GetObject("Schedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchWeb {
            get {
                object obj = ResourceManager.GetObject("SearchWeb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SendMail {
            get {
                object obj = ResourceManager.GetObject("SendMail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ShrinkFont {
            get {
                object obj = ResourceManager.GetObject("ShrinkFont", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon SignedOut {
            get {
                object obj = ResourceManager.GetObject("SignedOut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Spelling {
            get {
                object obj = ResourceManager.GetObject("Spelling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NewDataSet&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice minOccurs=&quot;0&quot; maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Values&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name=&quot;Symbol&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot; /&gt;
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string StockData {
            get {
                return ResourceManager.GetString("StockData", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Strikethrough {
            get {
                object obj = ResourceManager.GetObject("Strikethrough", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Subscript {
            get {
                object obj = ResourceManager.GetObject("Subscript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Superscript {
            get {
                object obj = ResourceManager.GetObject("Superscript", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Untitled Page&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        
        ///        body { font-family: Courier New; }
        ///        p { margin: 0px; }
        ///        .comment { color: green; }
        ///        .string { color: red; }
        ///        .resWord { color: blue; font-weight:bold; }
        ///        .type { color: teal; font-weight:bold; }
        ///        
        ///    &lt;/st [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Syntax {
            get {
                return ResourceManager.GetString("Syntax", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap tag {
            get {
                object obj = ResourceManager.GetObject("tag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot; &gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Untitled Page&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    body { font-family: Verdana; font-size: 9pt; }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;Nikola Tesla&lt;/h1&gt;
        ///    &lt;p&gt;
        ///        Nikola Tesla (10 July 1856 - 7 January 1943) was an inventor and a mechanical 
        ///        and electrical engineer.&lt;/p&gt;
        ///    &lt;p&gt;Tesla was born in th [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tesla {
            get {
                return ResourceManager.GetString("tesla", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Toolbox {
            get {
                object obj = ResourceManager.GetObject("Toolbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TotalSalesByCategory {
            get {
                return ResourceManager.GetString("TotalSalesByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NewDataSet&gt;
        ///  &lt;xs:schema id=&quot;NewDataSet&quot; xmlns=&quot;&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot;&gt;
        ///    &lt;xs:element name=&quot;NewDataSet&quot; msdata:IsDataSet=&quot;true&quot;&gt;
        ///      &lt;xs:complexType&gt;
        ///        &lt;xs:choice maxOccurs=&quot;unbounded&quot;&gt;
        ///          &lt;xs:element name=&quot;Tracks&quot;&gt;
        ///            &lt;xs:complexType&gt;
        ///              &lt;xs:sequence&gt;
        ///                &lt;xs:element name=&quot;Title&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot; /&gt;
        ///                &lt;xs:el [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;TextFiles&gt;
        ///  &lt;Customer&gt;
        ///    &lt;Install&gt;
        ///      &lt;Property Name=&quot;1720XP.txt&quot;&gt;12/5/2007&lt;/Property&gt;
        ///      &lt;Property Name=&quot;ArticleLinks.txt&quot;&gt;4/25/2008&lt;/Property&gt;
        ///      &lt;Property Name=&quot;how2run.txt&quot;&gt;7/18/2007&lt;/Property&gt;
        ///    &lt;/Install&gt;
        ///    &lt;Licensing&gt;
        ///      &lt;Property Name=&quot;licencsedControls.txt&quot;&gt;7/20/2007&lt;/Property&gt;
        ///      &lt;Property Name=&quot;licensingfix.txt&quot;&gt;3/12/2008&lt;/Property&gt;
        ///      &lt;Property Name=&quot;resourcenotes.txt&quot;&gt;3/3/2008&lt;/Property&gt;
        ///      &lt;Troubleshooting&gt;
        ///      [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TreeGroups {
            get {
                return ResourceManager.GetString("TreeGroups", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Underline {
            get {
                object obj = ResourceManager.GetObject("Underline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Undo {
            get {
                object obj = ResourceManager.GetObject("Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Unpinned {
            get {
                object obj = ResourceManager.GetObject("Unpinned", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap upLevel {
            get {
                object obj = ResourceManager.GetObject("upLevel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap User {
            get {
                object obj = ResourceManager.GetObject("User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Users {
            get {
                object obj = ResourceManager.GetObject("Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;C1DemoDataSet xmlns=&quot;http://tempuri.org/C1DemoDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;C1DemoDataSet&quot; targetNamespace=&quot;http://tempuri.org/C1DemoDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/C1DemoDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/C1DemoDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element name=&quot;C1DemoDataSet&quot; msdata:IsDataSet=&quot;true&quot; msda [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WeatherData {
            get {
                return ResourceManager.GetString("WeatherData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;NwindDataSet xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot;&gt;
        ///  &lt;xs:schema id=&quot;NwindDataSet&quot; targetNamespace=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:mstns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns=&quot;http://tempuri.org/NwindDataSet.xsd&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:msdata=&quot;urn:schemas-microsoft-com:xml-msdata&quot; xmlns:msprop=&quot;urn:schemas-microsoft-com:xml-msprop&quot; attributeFormDefault=&quot;qualified&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string YearlySalesByCategory {
            get {
                return ResourceManager.GetString("YearlySalesByCategory", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Zoom {
            get {
                object obj = ResourceManager.GetObject("Zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
